version: "3"

services:
  db:
    # image: mysql:8.0.33
    image: mariadb:10.3.28
    # platform: linux/x86_64
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony_app
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../club-simple-back/source/:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      - symfony_app
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../club-simple-back/source/:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    ports:
      - 8083:80
    networks:
      - symfony_app
    env_file:
      - .env.nginx.local
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

    networks:
      - symfony_app
volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:

networks:
  symfony_app:
